name:           macmade - msbuild
description:    GitHub Action for msbuild.
author:         macmade
branding:
    icon:       box
    color:      blue
runs:
    using:      'composite'
    steps:
        
        - name:     MSBuild - Setup
          id:       msbuild-setup
          uses:     microsoft/setup-msbuild@34cfbaee7f672c76950673338facd8a73f637506 # v1.1
          with:
            vs-prerelease: true
        
        - name:     MSBuild - NuGet
          id:       msbuild-nuget
          shell:    cmd
          env:
            SOLUTION: ${{ matrix.run-config[ 'solution' ] }}
          run:      msbuild -t:restore "%SOLUTION%"

        - name:     MSBuild - Build
          id:       msbuild-build
          shell:    cmd
          env:
            SOLUTION:       ${{ matrix.run-config[ 'solution' ] }}
            CONFIGURATION:  ${{ matrix.run-config[ 'configuration' ] }}
            PLATFORM:       ${{ matrix.run-config[ 'platform' ] }}
            TOOLSET:        ${{ matrix.run-config[ 'toolset' ] }}
          run:      msbuild "%SOLUTION%" /property:Configuration=%CONFIGURATION% /property:Platform="%PLATFORM%" /p:PreferredToolArchitecture=%TOOLSET%
