name:           macmade - msbuild
description:    GitHub Action for msbuild.
author:         macmade
branding:
    icon:       box
    color:      blue
runs:
    using:      'composite'
    steps:
        
        - name:     MSBuild - Setup
          id:       msbuild-setup
          uses:     microsoft/setup-msbuild@v1.0.3
        
        - name:     MSBuild - Build
          id:       msbuild-build
          shell:    cmd
          run:      msbuild ${{ matrix.run-config[ 'solution' ] }} /property:Configuration=${{ matrix.run-config[ 'configuration' ] }} /property:Platform=${{ matrix.run-config[ 'platform' ] }} /p:PreferredToolArchitecture=${{ matrix.run-config[ 'toolset' ] }}
